[package]
name = "try-arkworks"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-crypto-primitives = { version = "0.5.0", features = ["merkle_tree"] }
ark-std = "0.5.0"
ark-ff = "0.5.0"
ark-test-curves = { version = "0.5.0", features = ["bls12_381_curve"] }